# Generated by Django 4.1.1 on 2022-10-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="contact",
            name="is_favorite",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.TextField(),
        ),
    ]
