# Generated by Django 4.1.1 on 2022-10-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="address",
            field=models.TextField(max_length=50),
        ),
    ]
